library("tidyverse")
library("AbNames")
library("biomaRt")
library("org.Hs.eg.db")

source("data-raw/01_hgnc.R")
source("data-raw/02_ncbi.R")
source("data-raw/03_entrez_ensembl.R")
#source("data-raw/06_gene_aliases.R")
#source("data-raw/07_manual_matches.R")
#source("data-raw/08_antibody_registry.R")
#source("data-raw/09_check_aliases.R")
