---
title: "Standardize a SingleCellExperiment"
author: "Helen Lindsay"
package: AbNames
date: '2022-07-11'
output:
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{AbNames_SCE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This vignette shows how to standardize the names of the antibody-derived tags in
a CITE-seq experiment in SingleCellExperiment format.

To demonstrate, we will use the "kotliarov" dataset available in the package
"scRNAseq".  


```{r, message = FALSE}

#library(SingleCellMultiModal)
#cord_blood <- CITEseq(DataType="cord_blood", modes="scADT_Counts",
#                      dry.run=FALSE, DataClass = "SingleCellExperiment")
#cord_blood

# May not need much renaming....
library("scRNAseq")
kotliarov <- KotliarovPBMCData(mode = "adt")
head(rownames(kotliarov))

# Step by step method

# 1. Put into a data frame to allow matching to the CITEseq data set
df <- data.frame(Original = rownames(kotliarov),
                 Antigen = gsub("_PROT", "", rownames(kotliarov)))

# 2. Review suggested consensus names
# Antibodies are grouped by matches in catalogue number, clone, antigen name
# or gene identifier.  It is a good idea to review matches as errors in e.g.
# catalogue number will lead to incorrect matches.
df <- matchToCiteseq(df)
print(head(df))

# 3. Rename
new_nms <- structure(df[[2]], names = rownames(kotliarov))
kotliarov <- renameADT(kotliarov, new_nms)

head(rownames(kotliarov))


#library(CiteFuse)
#data("CITEseq_example", package = "CiteFuse")
#sce_citeseq <- preprocessing(CITEseq_example)
#rownames(altExp(sce_citeseq, "ADT"))
```
